#%RAML 1.0 DataType
type: object
properties:
  CorpAddressId:
    type: string
    required: false
  MailAddress1:
    type: string
    required: false
  MailAddress2:
    type: string
    required: false
  MailAddress3:
    type: string
    required: false
  MailCity:
    type: string
    required: false
  MailState:
    type: string
    required: false
  MailPostalCode:
    type: string
    required: false
  MailCountry:
    type: string
    required: false
  CentralPhoneNumber:
    type: string
    required: false
  CentralFaxNumber:
    type: string
    required: false
  Alternative1099Name:
    type: string
    required: false
  NameControl:
    type: string
    required: false
  PhysAddress1:
    type: string
    required: false
  PhysAddress2:
    type: string
    required: false
  PhysAddress3:
    type: string
    required: false
  PhysCity:
    type: string
    required: false
  PhysState:
    type: string
    required: false
  PhysPostalCode:
    type: string
    required: false
  PhysCountry:
    type: string
    required: false
  Incorporated:
    type: string
    required: false
  EmailAddress:
    type: string
    required: false
  Url:
    type: string
    required: false
  AddressId:
    type: string
    required: false
  Name:
    type: string
    required: false
  UserDefinedFields:
    type: string
    required: false
  ObjectName:
    type: string
    required: false