{
    "value": [
        {
            "po_no": 40418062,
            "line_no": 1,
            "company_no": "FFP",
            "location_id": 21000,
            "vendor_id": 351934,
            "carrier_id": "859394",
            "ups_code": null,
            "Shipping_instruction": null,
            "item_id": "HFU640UY020J",
            "supplier_part_no": "HFU640UY020J",
            "qty_received": 0,
            "extended_desc": "CARTRIDGE PTM HIGH FLOW P2088825",
            "supplier_acknowledgement": "345678",
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": null,
            "supplier_id": 351935,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418062",
            "BEG05_PODate": "20260324",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "sulagna lenka",
            "PER04_email_address": "sulagnalenka@flowcontrolgroup.com",
            "REF_ST_02_Location_Id": 21000,
            "REF_ZZ_02_Vendor_Id": 351934,
            "DTM_002_DeliveryReq": "20260324",
            "DTM_010_Requested": "20260324",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": null,
            "TD503_CarrierSCAC": null,
            "TD505_Routing": "SEE NOTES - CC",
            "FOB02": "PP",
            "FOB03": "Prepaid",
            "FOB02_Description": null,
            "N1_BY_Name": "FLUID FLOW PRODUCTS LLC",
            "N3_BY_Addr1": "3915 Shopton Rd",
            "N4_BY_City": "Charlotte",
            "N4_BY_State": "NC",
            "N4_BY_Zip": "28217-3047",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 351935,
            "N3_SU_Addr1": "770 PENNSYLVANIA DRIVE",
            "N4_SU_City": "EXTON",
            "N4_SU_State": "PA",
            "N4_SU_Zip": "19341",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "1",
            "PO1_02_QtyOrdered": 16,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 851.98,
            "PO1_07_item_id": "HFU640UY020J",
            "N901_LINE_Topic": "MC | SI",
            "N902_LINE_Note": "237 | LTL wkly consolidated shipment by online sys. Ship by 3rd party billing to: Flow Control Group, c/o SIMPLIFIED LOGISTICS, LLC, PO Box 40088, Bay Village, OH 44140-0088",
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "PTMS HFU640UY020J",
            "PID05_Extended_Desc": "CARTRIDGE PTM HIGH FLOW P2088825"
        },
        {
            "po_no": 40418062,
            "line_no": 2,
            "company_no": "FFP",
            "location_id": 21000,
            "vendor_id": 351934,
            "carrier_id": "859394",
            "ups_code": null,
            "Shipping_instruction": null,
            "item_id": "HFU640UY045J",
            "supplier_part_no": "HFU640UY045J",
            "qty_received": 0,
            "extended_desc": "P2085153 HIGH FLOW ULTIPLEAT",
            "supplier_acknowledgement": "345678",
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": null,
            "supplier_id": 351935,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418062",
            "BEG05_PODate": "20260324",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "sulagna lenka",
            "PER04_email_address": "sulagnalenka@flowcontrolgroup.com",
            "REF_ST_02_Location_Id": 21000,
            "REF_ZZ_02_Vendor_Id": 351934,
            "DTM_002_DeliveryReq": "20260324",
            "DTM_010_Requested": "20260324",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": null,
            "TD503_CarrierSCAC": null,
            "TD505_Routing": "SEE NOTES - CC",
            "FOB02": "PP",
            "FOB03": "Prepaid",
            "FOB02_Description": null,
            "N1_BY_Name": "FLUID FLOW PRODUCTS LLC",
            "N3_BY_Addr1": "3915 Shopton Rd",
            "N4_BY_City": "Charlotte",
            "N4_BY_State": "NC",
            "N4_BY_Zip": "28217-3047",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 351935,
            "N3_SU_Addr1": "770 PENNSYLVANIA DRIVE",
            "N4_SU_City": "EXTON",
            "N4_SU_State": "PA",
            "N4_SU_Zip": "19341",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "2",
            "PO1_02_QtyOrdered": 8,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 614.22,
            "PO1_07_item_id": "HFU640UY045J",
            "N901_LINE_Topic": "MC",
            "N902_LINE_Note": "237",
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "PTMS P2085153 HFU640UY045J",
            "PID05_Extended_Desc": "P2085153 HIGH FLOW ULTIPLEAT"
        },
        {
            "po_no": 40418062,
            "line_no": 3,
            "company_no": "FFP",
            "location_id": 21000,
            "vendor_id": 351934,
            "carrier_id": "859394",
            "ups_code": null,
            "Shipping_instruction": null,
            "item_id": "WF3P02018JTIMONIUM",
            "supplier_part_no": "WF3P02018JTIMONIUM",
            "qty_received": 0,
            "extended_desc": null,
            "supplier_acknowledgement": "345678",
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": null,
            "supplier_id": 351935,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418062",
            "BEG05_PODate": "20260324",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "sulagna lenka",
            "PER04_email_address": "sulagnalenka@flowcontrolgroup.com",
            "REF_ST_02_Location_Id": 21000,
            "REF_ZZ_02_Vendor_Id": 351934,
            "DTM_002_DeliveryReq": "20260324",
            "DTM_010_Requested": "20260324",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": null,
            "TD503_CarrierSCAC": null,
            "TD505_Routing": "SEE NOTES - CC",
            "FOB02": "PP",
            "FOB03": "Prepaid",
            "FOB02_Description": null,
            "N1_BY_Name": "FLUID FLOW PRODUCTS LLC",
            "N3_BY_Addr1": "3915 Shopton Rd",
            "N4_BY_City": "Charlotte",
            "N4_BY_State": "NC",
            "N4_BY_Zip": "28217-3047",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 351935,
            "N3_SU_Addr1": "770 PENNSYLVANIA DRIVE",
            "N4_SU_City": "EXTON",
            "N4_SU_State": "PA",
            "N4_SU_Zip": "19341",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "3",
            "PO1_02_QtyOrdered": 960,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 75.59,
            "PO1_07_item_id": "WF3P02018JTIMONIUM",
            "N901_LINE_Topic": "MC | SI",
            "N902_LINE_Note": "237 | LTL wkly consolidated shipment by online sys. Ship by 3rd party billing to: Flow Control Group, c/o SIMPLIFIED LOGISTICS, LLC, PO Box 40088, Bay Village, OH 44140-0088",
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "PFTS WF3P02018JTIMONIUM",
            "PID05_Extended_Desc": null
        },
        {
            "po_no": 40418066,
            "line_no": 1,
            "company_no": "FFP",
            "location_id": 21000,
            "vendor_id": 351934,
            "carrier_id": "340475",
            "ups_code": null,
            "Shipping_instruction": null,
            "item_id": "HFU640UY020J",
            "supplier_part_no": "HFU640UY020J",
            "qty_received": 0,
            "extended_desc": "CARTRIDGE PTM HIGH FLOW P2088825",
            "supplier_acknowledgement": "345",
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": null,
            "supplier_id": 351935,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418066",
            "BEG05_PODate": "20260326",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "sulagna lenka",
            "PER04_email_address": "sulagnalenka@flowcontrolgroup.com",
            "REF_ST_02_Location_Id": 21000,
            "REF_ZZ_02_Vendor_Id": 351934,
            "DTM_002_DeliveryReq": "20260326",
            "DTM_010_Requested": "20260326",
            "N902_HDR_Note": "Testing 1 | Testing for Brad",
            "MSG01_Shipping_instruction": null,
            "TD503_CarrierSCAC": null,
            "TD505_Routing": "Best Way",
            "FOB02": "PP",
            "FOB03": "Prepaid",
            "FOB02_Description": null,
            "N1_BY_Name": "FLUID FLOW PRODUCTS LLC",
            "N3_BY_Addr1": "3915 Shopton Rd",
            "N4_BY_City": "Charlotte",
            "N4_BY_State": "NC",
            "N4_BY_Zip": "28217-3047",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 351935,
            "N3_SU_Addr1": "770 PENNSYLVANIA DRIVE",
            "N4_SU_City": "EXTON",
            "N4_SU_State": "PA",
            "N4_SU_Zip": "19341",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "1",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 851.98,
            "PO1_07_item_id": "HFU640UY020J",
            "N901_LINE_Topic": "PO Line test1 | PO Line test 2",
            "N902_LINE_Note": "PO Line testing1 | PO Line testing 2",
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "PTMS HFU640UY020J",
            "PID05_Extended_Desc": "CARTRIDGE PTM HIGH FLOW P2088825"
        },
        {
            "po_no": 40418071,
            "line_no": 1,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000080156",
            "supplier_part_no": "FES132041",
            "qty_received": 0,
            "extended_desc": "QS-G1/4-10-50",
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "1",
            "PO1_02_QtyOrdered": 50,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 0.65,
            "PO1_07_item_id": "1000080156",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": "QS-G1/4-10-50"
        },
        {
            "po_no": 40418071,
            "line_no": 2,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085335",
            "supplier_part_no": "FES163494",
            "qty_received": 0,
            "extended_desc": null,
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "2",
            "PO1_02_QtyOrdered": 3,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 2903.9,
            "PO1_07_item_id": "1000085335",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "DNC-125-300-PPV-A-KP",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": null
        },
        {
            "po_no": 40418071,
            "line_no": 3,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085336",
            "supplier_part_no": "FES1463766",
            "qty_received": 0,
            "extended_desc": "DSBC-50-X-PPVA-N3",
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "3",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 156.01,
            "PO1_07_item_id": "1000085336",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "X=130",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": "DSBC-50-X-PPVA-N3"
        },
        {
            "po_no": 40418071,
            "line_no": 4,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085337",
            "supplier_part_no": "FES569926",
            "qty_received": 0,
            "extended_desc": null,
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "4",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 1298.77,
            "PO1_07_item_id": "1000085337",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "34P-LK-SF-U3ABB5A-JEJ3EJMSLL",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": null
        },
        {
            "po_no": 40418071,
            "line_no": 5,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085338",
            "supplier_part_no": "FES531030",
            "qty_received": 0,
            "extended_desc": null,
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "5",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 427.17,
            "PO1_07_item_id": "1000085338",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "MSB6-1/2:C4:J3:F1:V39-WP",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": null
        },
        {
            "po_no": 40418071,
            "line_no": 6,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000083424",
            "supplier_part_no": "FES165077",
            "qty_received": 0,
            "extended_desc": "HEL-1/4-D-MINI",
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "6",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 73.25,
            "PO1_07_item_id": "1000083424",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": null,
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": "HEL-1/4-D-MINI"
        },
        {
            "po_no": 40418071,
            "line_no": 7,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085339",
            "supplier_part_no": "FES163336",
            "qty_received": 0,
            "extended_desc": "DNC-40-X-PPV-A",
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "7",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 220.44,
            "PO1_07_item_id": "1000085339",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "X=750",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": "DNC-40-X-PPV-A"
        },
        {
            "po_no": 40418071,
            "line_no": 8,
            "company_no": "SFP",
            "location_id": 47000,
            "vendor_id": 234093,
            "carrier_id": "117666",
            "ups_code": null,
            "Shipping_instruction": "354901331",
            "item_id": "1000085340",
            "supplier_part_no": "FES532447",
            "qty_received": 0,
            "extended_desc": null,
            "supplier_acknowledgement": null,
            "edi_po_status": "Ready",
            "po_type": "B",
            "sales_order_number": null,
            "scac_edi": "RDWY",
            "supplier_id": 234093,
            "BEG01_PurposeCode": "00",
            "BEG02_POTypeCode": "SA",
            "BEG03_PONumber": "40418071",
            "BEG05_PODate": "20260330",
            "CUR02_currency": "U.S. Dollars",
            "PER02_Name": "Jessica Sansote",
            "PER04_email_address": "jessicas@shaltzautomation.com",
            "REF_ST_02_Location_Id": 47000,
            "REF_ZZ_02_Vendor_Id": 234093,
            "DTM_002_DeliveryReq": "20260330",
            "DTM_010_Requested": "20260330",
            "N902_HDR_Note": null,
            "MSG01_Shipping_instruction": "354901331",
            "TD503_CarrierSCAC": "RDWY",
            "TD505_Routing": "YRC Freight",
            "FOB02": "CC",
            "FOB03": "Collect",
            "FOB02_Description": null,
            "N1_BY_Name": "SHALTZ AUTOMATION",
            "N3_BY_Addr1": "5190 Exchange Drive",
            "N4_BY_City": "Flint",
            "N4_BY_State": "MI",
            "N4_BY_Zip": "48507",
            "N4_BY_Country": "US",
            "N1_ST_Name": null,
            "N3_ST_Addr1": null,
            "N4_ST_City": null,
            "N4_ST_State": null,
            "N4_ST_Zip": null,
            "N4_ST_Country": null,
            "N1_SU_ID": 234093,
            "N3_SU_Addr1": "1377 MOTOR PKWY",
            "N4_SU_City": "ISLANDIA",
            "N4_SU_State": "NY",
            "N4_SU_Zip": "11749-5258",
            "N4_SU_Country": "US",
            "PO1_01_AssignedID": "8",
            "PO1_02_QtyOrdered": 1,
            "PO1_03_UOM": "EA",
            "PO1_04_UnitPrice": 815.18,
            "PO1_07_item_id": "1000085340",
            "N901_LINE_Topic": null,
            "N902_LINE_Note": null,
            "PID05_LineConfig1": "DGC-25-275-KF-PPV-A",
            "PID05_2nd_LineConfig2": null,
            "PID05_Description": "FESTO",
            "PID05_Extended_Desc": null
        }
    ]
}
