# Prod Secure Configuration

email:
  password: "![yARA7CTFDm1RB656w4BiSsDG29F7MxpbHvdCQy8NJHg=]"
 
https:
  keystore:
    keypass: "![pkxKBdQGF3QeAOp3OsCpjg==]"
    storepass: "![pkxKBdQGF3QeAOp3OsCpjg==]]"
    
apm.api:
  accessToken:
    clientId: "![nKOkzX0lFGbJilfe+ocSOqiOOWvm74KqVEg1qTp9D4NU0GoYZyjFarGsan0enM27]"
    clientSecret: "![pnqApqHkhHt7a5alJnjeWLgYYo7hOayULEkiOkJgkzSL9aE5pD8Xi1q1oeQxfGa1]"
    grantType: "![yptchScYBV2tPk53cfWu4t6m74caJVQR41SyU+mZKLA=]" 