anypoint:
  platform:
    client_secret: "![cObUZrv53wISMgU1UPso8WfU3yfHq9DCDWKrUqv6v1rNYzSXnkBM++fdSjsTORBa]"
https:
  key:
    password: "![pkxKBdQGF3QeAOp3OsCpjg==]"
  keystore:
    password: "![pkxKBdQGF3QeAOp3OsCpjg==]"
  truststore:
    password: "![pkxKBdQGF3QeAOp3OsCpjg==]"
P21api:
  password: "![58pYPpaKvIc8tnBp/CbRJA==]"
p21Db:
  password: "![58pYPpaKvIc8tnBp/CbRJA==]"
